// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mbcwksjsvzgtfcfdgkrv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1iY3drc2pzdnpndGZjZmRna3J2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0MTQ5MjIsImV4cCI6MjA2Mjk5MDkyMn0.AQ-UJqsC3DmZPmQVEQu0lxqfRjaCEhnj9ZkfA-WvSDQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);